/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectedRouteImport } from './routes/connected'
import { Route as CoupleRouteImport } from './routes/couple'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DateRouteImport } from './routes/date'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as DevRouteImport } from './routes/dev'
import { Route as FinaleRouteImport } from './routes/finale'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as KeepRouteImport } from './routes/keep'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BeginPartnerRouteImport } from './routes/begin.$partner'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as RevealPartnerRouteImport } from './routes/reveal.$partner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedRoute = ConnectedRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupleRoute = CoupleRouteImport.update({
  id: '/couple',
  path: '/couple',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const FinaleRoute = FinaleRouteImport.update({
  id: '/finale',
  path: '/finale',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepRoute = KeepRouteImport.update({
  id: '/keep',
  path: '/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginPartnerRoute = BeginPartnerRouteImport.update({
  id: '/begin/$partner',
  path: '/begin/$partner',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealPartnerRoute = RevealPartnerRouteImport.update({
  id: '/reveal/$partner',
  path: '/reveal/$partner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRoute
  '/couple': typeof CoupleRoute
  '/create': typeof CreateRoute
  '/date': typeof DateRoute
  '/dates': typeof DatesRoute
  '/dev': typeof DevRoute
  '/finale': typeof FinaleRoute
  '/generating': typeof GeneratingRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invite': typeof InviteRoute
  '/keep': typeof KeepRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/waiting': typeof WaitingRoute
  '/welcome': typeof WelcomeRoute
  '/begin/$partner': typeof BeginPartnerRoute
  '/join/$code': typeof JoinCodeRoute
  '/reveal/$partner': typeof RevealPartnerRoute
  '/join/': typeof JoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRoute
  '/couple': typeof CoupleRoute
  '/create': typeof CreateRoute
  '/date': typeof DateRoute
  '/dates': typeof DatesRoute
  '/dev': typeof DevRoute
  '/finale': typeof FinaleRoute
  '/generating': typeof GeneratingRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invite': typeof InviteRoute
  '/keep': typeof KeepRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/waiting': typeof WaitingRoute
  '/welcome': typeof WelcomeRoute
  '/begin/$partner': typeof BeginPartnerRoute
  '/join/$code': typeof JoinCodeRoute
  '/reveal/$partner': typeof RevealPartnerRoute
  '/join': typeof JoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connected': typeof ConnectedRoute
  '/couple': typeof CoupleRoute
  '/create': typeof CreateRoute
  '/date': typeof DateRoute
  '/dates': typeof DatesRoute
  '/dev': typeof DevRoute
  '/finale': typeof FinaleRoute
  '/generating': typeof GeneratingRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invite': typeof InviteRoute
  '/keep': typeof KeepRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/waiting': typeof WaitingRoute
  '/welcome': typeof WelcomeRoute
  '/begin/$partner': typeof BeginPartnerRoute
  '/join/$code': typeof JoinCodeRoute
  '/reveal/$partner': typeof RevealPartnerRoute
  '/join/': typeof JoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connected'
    | '/couple'
    | '/create'
    | '/date'
    | '/dates'
    | '/dev'
    | '/finale'
    | '/generating'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/invite'
    | '/keep'
    | '/partner'
    | '/profile'
    | '/recap'
    | '/signin'
    | '/signup'
    | '/waiting'
    | '/welcome'
    | '/begin/$partner'
    | '/join/$code'
    | '/reveal/$partner'
    | '/join/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connected'
    | '/couple'
    | '/create'
    | '/date'
    | '/dates'
    | '/dev'
    | '/finale'
    | '/generating'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/invite'
    | '/keep'
    | '/partner'
    | '/profile'
    | '/recap'
    | '/signin'
    | '/signup'
    | '/waiting'
    | '/welcome'
    | '/begin/$partner'
    | '/join/$code'
    | '/reveal/$partner'
    | '/join'
  id:
    | '__root__'
    | '/'
    | '/connected'
    | '/couple'
    | '/create'
    | '/date'
    | '/dates'
    | '/dev'
    | '/finale'
    | '/generating'
    | '/guest'
    | '/home'
    | '/how-it-works'
    | '/invite'
    | '/keep'
    | '/partner'
    | '/profile'
    | '/recap'
    | '/signin'
    | '/signup'
    | '/waiting'
    | '/welcome'
    | '/begin/$partner'
    | '/join/$code'
    | '/reveal/$partner'
    | '/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectedRoute: typeof ConnectedRoute
  CoupleRoute: typeof CoupleRoute
  CreateRoute: typeof CreateRoute
  DateRoute: typeof DateRoute
  DatesRoute: typeof DatesRoute
  DevRoute: typeof DevRoute
  FinaleRoute: typeof FinaleRoute
  GeneratingRoute: typeof GeneratingRoute
  GuestRoute: typeof GuestRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InviteRoute: typeof InviteRoute
  KeepRoute: typeof KeepRoute
  PartnerRoute: typeof PartnerRoute
  ProfileRoute: typeof ProfileRoute
  RecapRoute: typeof RecapRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  WaitingRoute: typeof WaitingRoute
  WelcomeRoute: typeof WelcomeRoute
  BeginPartnerRoute: typeof BeginPartnerRoute
  JoinCodeRoute: typeof JoinCodeRoute
  RevealPartnerRoute: typeof RevealPartnerRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected': {
      id: '/connected'
      path: '/connected'
      fullPath: '/connected'
      preLoaderRoute: typeof ConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couple': {
      id: '/couple'
      path: '/couple'
      fullPath: '/couple'
      preLoaderRoute: typeof CoupleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date': {
      id: '/date'
      path: '/date'
      fullPath: '/date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finale': {
      id: '/finale'
      path: '/finale'
      fullPath: '/finale'
      preLoaderRoute: typeof FinaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep': {
      id: '/keep'
      path: '/keep'
      fullPath: '/keep'
      preLoaderRoute: typeof KeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin/$partner': {
      id: '/begin/$partner'
      path: '/begin/$partner'
      fullPath: '/begin/$partner'
      preLoaderRoute: typeof BeginPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal/$partner': {
      id: '/reveal/$partner'
      path: '/reveal/$partner'
      fullPath: '/reveal/$partner'
      preLoaderRoute: typeof RevealPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectedRoute: ConnectedRoute,
  CoupleRoute: CoupleRoute,
  CreateRoute: CreateRoute,
  DateRoute: DateRoute,
  DatesRoute: DatesRoute,
  DevRoute: DevRoute,
  FinaleRoute: FinaleRoute,
  GeneratingRoute: GeneratingRoute,
  GuestRoute: GuestRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  InviteRoute: InviteRoute,
  KeepRoute: KeepRoute,
  PartnerRoute: PartnerRoute,
  ProfileRoute: ProfileRoute,
  RecapRoute: RecapRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  WaitingRoute: WaitingRoute,
  WelcomeRoute: WelcomeRoute,
  BeginPartnerRoute: BeginPartnerRoute,
  JoinCodeRoute: JoinCodeRoute,
  RevealPartnerRoute: RevealPartnerRoute,
  JoinIndexRoute: JoinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
