export type Vibe =
  | "surprise"
  | "funny"
  | "romantic"
  | "mysterious"
  | "cinematic"
  | "weird"
  | "wholesome";

export type Character = {
  id: string;
  emoji: string;
  name: string;
  description: string;
  energy: string[];
  act: string[];
  dress: string;
  voice: string;
  rule: string;
  starter?: string;
  tags: Exclude<Vibe, "surprise">[];
};

/**
 * Mock character library. Structured so the generator can later be swapped
 * for a real generation service without touching the UI.
 */
export const CHARACTERS: Character[] = [
  {
    id: "chemist",
    emoji: "🧪",
    name: "The Eccentric Chemist",
    description:
      "You are brilliant, curious, slightly obsessive, and fascinated by things nobody else finds interesting.",
    energy: ["Curious", "Intense", "Slightly chaotic"],
    act: [
      "Treat everyday things like scientific discoveries.",
      "Become unnecessarily excited about small details.",
      "Occasionally take notes.",
      "Ask strange questions.",
      "Speak confidently about things nobody asked about.",
    ],
    dress:
      "White shirt, glasses, notebook, slightly messy hair. Anything that makes you look like you haven't left the laboratory in three days.",
    voice: "Confident. Curious. Slightly dramatic.",
    rule: "Never call your food “food.” Call it a specimen.",
    starter:
      "I've been conducting an experiment all week. I think tonight might finally give me the results.",
    tags: ["weird", "funny", "cinematic"],
  },
  {
    id: "pilot",
    emoji: "✈️",
    name: "The Overconfident Pilot",
    description:
      "You have flown through storms nobody else survived, and you will mention this at least four times tonight.",
    energy: ["Assured", "Warm", "Faintly ridiculous"],
    act: [
      "Compare everything to altitude, turbulence or weather.",
      "Reassure people who are not worried.",
      "Check imaginary instruments.",
      "Refer to the evening as “our route.”",
    ],
    dress: "Crisp shirt, aviators hooked on the collar, watch worn too seriously.",
    voice: "Calm cockpit announcer. Unshakeable.",
    rule: "Announce anything that changes, like a captain would.",
    starter: "Cabin crew, seats for departure. You're in good hands tonight.",
    tags: ["funny", "cinematic"],
  },
  {
    id: "food-critic",
    emoji: "🍽️",
    name: "The Ruthless Food Critic",
    description:
      "You have eaten everywhere and been disappointed nearly everywhere. Tonight might be different. Probably not.",
    energy: ["Precise", "Withering", "Secretly delighted"],
    act: [
      "Describe textures in painful detail.",
      "Award scores nobody asked for.",
      "Smell things before tasting them.",
      "Pause dramatically before verdicts.",
    ],
    dress: "Dark blazer, quiet luxury, one small notebook you never explain.",
    voice: "Slow, deliberate, faintly bored.",
    rule: "Rate at least three things out of ten tonight.",
    starter: "I'll be honest, my expectations tonight are historically low.",
    tags: ["funny", "cinematic"],
  },
  {
    id: "journalist",
    emoji: "🗞️",
    name: "The Investigative Journalist",
    description:
      "You are chasing a story and you are almost certain the person across from you is part of it.",
    energy: ["Sharp", "Persistent", "Charming"],
    act: [
      "Ask one follow-up question too many.",
      "Repeat their answers back slowly.",
      "Say “off the record” often.",
      "Write things down at odd moments.",
    ],
    dress: "Trench-adjacent coat, worn notebook, pen behind the ear.",
    voice: "Fast, friendly, relentless.",
    rule: "Everything they say is a quote you may print.",
    starter: "Before we start — do you mind if I take notes?",
    tags: ["mysterious", "cinematic"],
  },
  {
    id: "fashion-designer",
    emoji: "🧵",
    name: "The Temperamental Fashion Designer",
    description:
      "You see silhouettes everywhere and you have very strong feelings about the lighting in here.",
    energy: ["Dramatic", "Exacting", "Fabulous"],
    act: [
      "Critique the room's palette.",
      "Redesign a stranger's outfit out loud.",
      "Gasp at good tailoring.",
      "Declare something “over.”",
    ],
    dress: "One bold silhouette. Sunglasses indoors optional but encouraged.",
    voice: "Clipped, theatrical, allergic to beige.",
    rule: "Announce a new trend and insist you invented it.",
    starter: "Don't move. That's the shape of the whole collection.",
    tags: ["funny", "cinematic"],
  },
  {
    id: "archaeologist",
    emoji: "🏺",
    name: "The Dusty Archaeologist",
    description:
      "You have been in the field too long and everything here looks like an artifact worth carbon dating.",
    energy: ["Rugged", "Wondering", "Slightly sunburnt"],
    act: [
      "Handle objects like they're 4,000 years old.",
      "Tell a story about a dig nobody can verify.",
      "Brush dust off things that are clean.",
    ],
    dress: "Linen, boots, something with too many pockets.",
    voice: "Low, warm, weathered.",
    rule: "Every object on the table has a civilization behind it.",
    starter: "This place — I swear I've excavated a version of it before.",
    tags: ["cinematic", "romantic"],
  },
  {
    id: "professor",
    emoji: "📖",
    name: "The Distracted Professor",
    description:
      "Your mind is three lectures ahead and you are delighted to be interrupted.",
    energy: ["Gentle", "Rambling", "Brilliant"],
    act: [
      "Begin a tangent, forget the point, arrive somewhere better.",
      "Quote someone incorrectly with confidence.",
      "Assign small homework.",
    ],
    dress: "Knitwear, worn jacket, glasses pushed up onto your head.",
    voice: "Soft, thoughtful, prone to long pauses.",
    rule: "Turn one ordinary moment into a tiny lecture.",
    starter: "Sorry — where were we? Ah. Yes. Everything.",
    tags: ["wholesome", "romantic"],
  },
  {
    id: "celebrity",
    emoji: "🕶️",
    name: "The Incognito Celebrity",
    description:
      "You are famous, you are hiding it badly, and you would rather nobody made a scene.",
    energy: ["Cool", "Guarded", "Amused"],
    act: [
      "Scan the room for photographers.",
      "Lower your voice when saying your own name.",
      "Thank people for their discretion.",
    ],
    dress: "Cap, dark glasses, expensive basics.",
    voice: "Hushed, gracious, practiced.",
    rule: "Never confirm who you are. Never deny it either.",
    starter: "Let's sit somewhere with fewer sightlines.",
    tags: ["funny", "mysterious"],
  },
  {
    id: "billionaire-broke",
    emoji: "💼",
    name: "The Billionaire Pretending To Be Broke",
    description:
      "You are conducting a social experiment about ordinary life and failing it constantly.",
    energy: ["Slick", "Clueless", "Earnest"],
    act: [
      "Guess prices catastrophically wrong.",
      "Mention your helicopter, then correct yourself.",
      "Marvel at normal things.",
    ],
    dress: "Deliberately plain clothes, one accidentally expensive detail.",
    voice: "Breezy, over-explaining.",
    rule: "Insist you are extremely normal at least twice.",
    starter: "I love it here. So grounded. So... affordable, apparently.",
    tags: ["funny", "weird"],
  },
  {
    id: "chef",
    emoji: "👨‍🍳",
    name: "The Retired Michelin Chef",
    description:
      "You gave up the kitchen but the kitchen never gave up you.",
    energy: ["Exacting", "Passionate", "Nostalgic"],
    act: [
      "Diagnose every dish by smell.",
      "Explain how you'd fix it, kindly.",
      "Talk about salt with real emotion.",
    ],
    dress: "Rolled sleeves, apron optional, forearms of a person who has suffered.",
    voice: "Gruff, generous, sudden warmth.",
    rule: "Compliment one thing sincerely and one thing insincerely.",
    starter: "Order whatever you like. I'll be judging silently. Mostly.",
    tags: ["romantic", "funny"],
  },
  {
    id: "athlete",
    emoji: "🏅",
    name: "The Professional Athlete",
    description:
      "Everything is training. Dinner is training. Conversation is training.",
    energy: ["Driven", "Direct", "Endearing"],
    act: [
      "Turn small decisions into strategy.",
      "Hydrate aggressively.",
      "Give a pep talk nobody requested.",
    ],
    dress: "Sharp but sporty. Something you could sprint in.",
    voice: "Focused, motivational, slightly out of breath.",
    rule: "Refer to tonight as a match with two winners.",
    starter: "I've been visualising this all week. Let's execute.",
    tags: ["funny", "wholesome"],
  },
  {
    id: "art-collector",
    emoji: "🖼️",
    name: "The Art Collector",
    description:
      "You buy things you don't understand and explain them to people who didn't ask.",
    energy: ["Refined", "Pretentious", "Charming"],
    act: [
      "Frame moments with your hands.",
      "Attribute meaning to accidents.",
      "Compare everything to a piece in your collection.",
    ],
    dress: "Monochrome, sculptural glasses, one strange ring.",
    voice: "Languid, appreciative, murmuring.",
    rule: "Declare one ordinary object “an important work.”",
    starter: "I'm not saying I'd buy this room, but I'd consider a loan.",
    tags: ["cinematic", "romantic"],
  },
  {
    id: "conspiracy",
    emoji: "📌",
    name: "The Conspiracy Theorist",
    description:
      "You've connected the strings and tonight, at last, someone is listening.",
    energy: ["Wired", "Whispering", "Utterly certain"],
    act: [
      "Glance at the ceiling for cameras.",
      "Connect two unrelated facts triumphantly.",
      "Ask them to keep this between you two.",
    ],
    dress: "Layers, a folded piece of paper you refuse to unfold.",
    voice: "Low, urgent, occasionally too loud.",
    rule: "Name one everyday thing as part of the plan.",
    starter: "Don't react — but the person by the window has been here before.",
    tags: ["funny", "weird", "mysterious"],
  },
  {
    id: "vampire",
    emoji: "🧛",
    name: "The Reluctant Vampire",
    description:
      "Four hundred years old, deeply tired of small talk, unexpectedly soft.",
    energy: ["Elegant", "Weary", "Magnetic"],
    act: [
      "Reference decades like they were last week.",
      "Decline things politely and mysteriously.",
      "Compliment their pulse. Gently.",
    ],
    dress: "Dark colours, high collar, one antique-looking item.",
    voice: "Slow, velvet, amused.",
    rule: "Never say the word “blood.” Say “vintage.”",
    starter: "Forgive me. I've been out of practice at this since 1912.",
    tags: ["mysterious", "romantic", "cinematic"],
  },
  {
    id: "pirate",
    emoji: "🏴‍☠️",
    name: "The Semi-Retired Pirate",
    description:
      "You left the sea, but the sea keeps writing.",
    energy: ["Boisterous", "Superstitious", "Sentimental"],
    act: [
      "Call the venue a port.",
      "Bargain over things with fixed prices.",
      "Toast loudly and often.",
    ],
    dress: "Boots, rings, a shirt with too much sleeve.",
    voice: "Big, rolling, a bit of gravel.",
    rule: "Refer to money as plunder.",
    starter: "I docked here for one night only. Make it count.",
    tags: ["funny", "weird"],
  },
  {
    id: "cowboy",
    emoji: "🤠",
    name: "The Quiet Cowboy",
    description:
      "You say very little and somehow it lands every time.",
    energy: ["Steady", "Laconic", "Kind"],
    act: [
      "Answer in six words or fewer.",
      "Watch the door.",
      "Tip an invisible hat.",
      "Call people by their first name, slowly.",
    ],
    dress: "Denim, boots, belt buckle with unearned confidence.",
    voice: "Low drawl, long pauses.",
    rule: "Say “ma'am” or “partner” at least five times.",
    starter: "Been ridin' all day just to sit down across from you.",
    tags: ["romantic", "funny", "cinematic"],
  },
  {
    id: "detective",
    emoji: "🕵️",
    name: "The Noir Detective",
    description:
      "The city's been quiet lately. Too quiet. And then you walked in.",
    energy: ["Brooding", "Observant", "Wry"],
    act: [
      "Narrate the evening in the past tense.",
      "Deduce something wildly wrong.",
      "Stare into the middle distance after any sentence.",
    ],
    dress: "Coat, dark shirt, collar up.",
    voice: "Gravel, monologue, cigarette-that-isn't-there.",
    rule: "Every ten minutes, narrate the scene out loud.",
    starter: "She sat down and the whole night rearranged itself.",
    tags: ["mysterious", "cinematic", "romantic"],
  },
  {
    id: "secret-agent",
    emoji: "🎯",
    name: "The Secret Agent",
    description:
      "You're on assignment. This is a cover. Behave accordingly.",
    energy: ["Composed", "Alert", "Devastatingly polite"],
    act: [
      "Sit facing the exits.",
      "Speak in mild code.",
      "Check your watch meaningfully.",
      "Deny everything charmingly.",
    ],
    dress: "Impeccable tailoring, nothing memorable, one perfect detail.",
    voice: "Smooth, quiet, controlled.",
    rule: "Never confirm what you do for a living.",
    starter: "I have exactly two hours. Let's not waste them.",
    tags: ["mysterious", "cinematic", "romantic"],
  },
  {
    id: "time-traveler",
    emoji: "⏳",
    name: "The Time Traveller",
    description:
      "You arrived from somewhere else and the timeline is behaving strangely tonight.",
    energy: ["Disoriented", "Delighted", "Urgent"],
    act: [
      "Marvel at ordinary technology.",
      "Predict something obvious.",
      "Warn about a very small future event.",
    ],
    dress: "Mismatched eras. Something that shouldn't go together.",
    voice: "Breathless, wondering.",
    rule: "Refer to today's date as if it's remarkable.",
    starter: "Quick question, and don't laugh: what year do you have it as?",
    tags: ["weird", "funny", "cinematic"],
  },
  {
    id: "alien-tourist",
    emoji: "👽",
    name: "The Alien Tourist",
    description:
      "You are visiting Earth for one evening and you have read the brochure.",
    energy: ["Polite", "Baffled", "Enthusiastic"],
    act: [
      "Describe human customs as an observer.",
      "Copy their gestures a second too late.",
      "Compliment the planet.",
    ],
    dress: "Very neat, very literal interpretation of human clothing.",
    voice: "Careful pronunciation. Formal.",
    rule: "Say “your species” at least three times.",
    starter: "Greetings. I am told this is a highly rated Earth activity.",
    tags: ["weird", "funny"],
  },
  {
    id: "fortune-teller",
    emoji: "🔮",
    name: "The Fortune Teller",
    description:
      "You see what's coming. Some of it is good. Some of it is dessert.",
    energy: ["Mystic", "Teasing", "Warm"],
    act: [
      "Read the room like a palm.",
      "Predict small things that then happen.",
      "Refuse to reveal one thing you saw.",
    ],
    dress: "Layered fabrics, rings, something that catches candlelight.",
    voice: "Low, lilting, unhurried.",
    rule: "Make one prediction that must come true tonight.",
    starter: "I knew you'd sit there. The cards were quite specific.",
    tags: ["mysterious", "romantic"],
  },
  {
    id: "wizard",
    emoji: "🧙",
    name: "The Off-Duty Wizard",
    description:
      "Magic is real, it is exhausting, and you are on your night off.",
    energy: ["Grand", "Tired", "Twinkly"],
    act: [
      "Attempt small spells that clearly fail.",
      "Blame minor inconveniences on a curse.",
      "Speak of centuries as “a busy period.”",
    ],
    dress: "Long coat, rings, something that could be a staff if you squint.",
    voice: "Sonorous, then suddenly ordinary.",
    rule: "Bless or curse one item on the table.",
    starter: "Ignore the lights flickering. That happens around me.",
    tags: ["weird", "funny", "cinematic"],
  },
  {
    id: "villain",
    emoji: "🎩",
    name: "The Charming Villain",
    description:
      "Your plan is nearly complete and you are in an excellent mood about it.",
    energy: ["Suave", "Menacing", "Delighted"],
    act: [
      "Monologue slightly too long.",
      "Compliment them like it's a threat.",
      "Laugh at the wrong moment.",
    ],
    dress: "Sharp, dark, one glint of something metallic.",
    voice: "Silk over steel.",
    rule: "Refer to your “plan” without ever explaining it.",
    starter: "Sit. Please. Everything is proceeding beautifully.",
    tags: ["cinematic", "mysterious", "funny"],
  },
  {
    id: "royal-heir",
    emoji: "👑",
    name: "The Runaway Royal Heir",
    description:
      "You slipped the palace for one night of being nobody at all.",
    energy: ["Gracious", "Curious", "Slightly lost"],
    act: [
      "Thank staff far too formally.",
      "Be enchanted by ordinary rituals.",
      "Glance over your shoulder for guards.",
    ],
    dress: "Understated but immaculate. Posture doing all the work.",
    voice: "Measured, warm, beautifully enunciated.",
    rule: "Never touch a door handle if you can help it.",
    starter: "Nobody here knows me. Do you understand how rare that is?",
    tags: ["romantic", "cinematic"],
  },
  {
    id: "ghost",
    emoji: "👻",
    name: "The Polite Ghost",
    description:
      "You have been haunting this general area for decades and tonight you'd like company.",
    energy: ["Wistful", "Gentle", "Faintly spooky"],
    act: [
      "Refer to the past with real affection.",
      "Claim you've been here “a while.”",
      "Go very still at random moments.",
    ],
    dress: "Pale colours, old-fashioned cut.",
    voice: "Soft, distant, unhurried.",
    rule: "Never admit you're a ghost. Only imply it.",
    starter: "I used to come here often. Very often. For years, actually.",
    tags: ["mysterious", "romantic", "weird"],
  },
  {
    id: "magician",
    emoji: "🎩",
    name: "The Amateur Magician",
    description:
      "You have three tricks. Two of them work. You will perform all three.",
    energy: ["Eager", "Showy", "Fragile"],
    act: [
      "Produce something from nowhere, badly.",
      "Demand a round of applause.",
      "Blame failures on the humidity.",
    ],
    dress: "Waistcoat, cuffs, at least one thing hidden up a sleeve.",
    voice: "Showman patter at full volume.",
    rule: "Say “nothing up my sleeve” before anything you do.",
    starter: "Pick a card. Not really. I don't have cards. But pick one.",
    tags: ["funny", "wholesome"],
  },
  {
    id: "socialite-1920s",
    emoji: "🥂",
    name: "The 1920s Socialite",
    description:
      "The party is wherever you are and it has been going since Tuesday.",
    energy: ["Sparkling", "Reckless", "Glamorous"],
    act: [
      "Toast strangers.",
      "Refer to everyone as darling.",
      "Be scandalised by something ordinary.",
    ],
    dress: "Fringe, shine, something that moves when you laugh.",
    voice: "Bright, transatlantic, dizzy.",
    rule: "Call at least three things “simply divine.”",
    starter: "Darling, you're late — the decade started ages ago.",
    tags: ["cinematic", "romantic", "funny"],
  },
  {
    id: "victorian-librarian",
    emoji: "📚",
    name: "The Victorian Librarian",
    description:
      "Silence is sacred, order is love, and you have opinions about noise.",
    energy: ["Prim", "Precise", "Secretly wild"],
    act: [
      "Shush distant sounds.",
      "Alphabetise something on the table.",
      "Recommend a book for their exact mood.",
    ],
    dress: "High collar, buttons, hair severely under control.",
    voice: "Crisp, hushed, faintly scandalised.",
    rule: "Whisper anything you consider improper.",
    starter: "I've reserved this hour. Kindly do not raise your voice.",
    tags: ["romantic", "funny", "cinematic"],
  },
  {
    id: "knight",
    emoji: "🛡️",
    name: "The Medieval Knight",
    description:
      "You have sworn an oath, and tonight the oath concerns this table.",
    energy: ["Noble", "Earnest", "Overly formal"],
    act: [
      "Vow things aloud.",
      "Offer protection from nothing.",
      "Address them by an invented title.",
    ],
    dress: "Heavy fabrics, boots, anything that could pass for armour.",
    voice: "Booming, sincere, archaic.",
    rule: "Begin at least one sentence with “I swear upon...”",
    starter: "My lady, I have ridden three days. The traffic was medieval.",
    tags: ["funny", "romantic"],
  },
  {
    id: "renaissance-artist",
    emoji: "🎨",
    name: "The Renaissance Artist",
    description:
      "You see light, shadow and divine proportion in a bowl of olives.",
    energy: ["Rapturous", "Moody", "Tender"],
    act: [
      "Frame their face with your hands.",
      "Despair about your unfinished masterpiece.",
      "Sketch on a napkin.",
    ],
    dress: "Loose shirt, paint-adjacent stains, hair with opinions.",
    voice: "Passionate, sighing, occasionally shouting.",
    rule: "Announce that you must paint one thing you see tonight.",
    starter: "Don't move. The light is doing something unforgivable to you.",
    tags: ["romantic", "cinematic"],
  },
  {
    id: "movie-star-1950s",
    emoji: "🎬",
    name: "The 1950s Movie Star",
    description:
      "The camera left years ago. You never told your face.",
    energy: ["Poised", "Glamorous", "Melancholy"],
    act: [
      "Pause for imaginary flashbulbs.",
      "Deliver ordinary lines like they're scripted.",
      "Refer to your “people.”",
    ],
    dress: "Old Hollywood: clean lines, red lip or slick hair, sunglasses.",
    voice: "Rich, rehearsed, cinematic.",
    rule: "Turn to your best side before any important sentence.",
    starter: "They said this town would forget me. They were half right.",
    tags: ["cinematic", "romantic"],
  },
  {
    id: "rock-star-1980s",
    emoji: "🎸",
    name: "The 1980s Rock Star",
    description:
      "The tour ended. The volume did not.",
    energy: ["Loud", "Swaggering", "Surprisingly sweet"],
    act: [
      "Reference the tour bus.",
      "Sign something nobody asked you to sign.",
      "Air guitar during pauses.",
    ],
    dress: "Leather, big hair, sunglasses at night.",
    voice: "Raspy, loud, laughing.",
    rule: "Call everyone “legend.”",
    starter: "Sorry I'm late — soundcheck ran long. In my head.",
    tags: ["funny", "cinematic"],
  },
  {
    id: "worst-detective",
    emoji: "🔍",
    name: "The World's Worst Detective",
    description:
      "You solve nothing with total confidence.",
    energy: ["Certain", "Wrong", "Unstoppable"],
    act: [
      "Accuse innocent objects.",
      "Reach conclusions from nothing.",
      "Announce breakthroughs every ten minutes.",
    ],
    dress: "Coat, magnifier, notebook with two pages used.",
    voice: "Grand declarations, mid-sentence doubt.",
    rule: "Solve one crime that didn't happen.",
    starter: "Don't panic. But I believe someone here ordered something.",
    tags: ["funny", "weird"],
  },
  {
    id: "secretly-famous",
    emoji: "🌟",
    name: "The Person Who Thinks They're Secretly Famous",
    description:
      "Nobody recognises you and you find that suspicious.",
    energy: ["Hopeful", "Delusional", "Warm"],
    act: [
      "Prepare for autographs that never come.",
      "Interpret glances as recognition.",
      "Mention your “fans” quietly.",
    ],
    dress: "Disguise that draws maximum attention.",
    voice: "Modest brag, permanently.",
    rule: "Thank at least one stranger for their support.",
    starter: "Keep it down — I think that table clocked me.",
    tags: ["funny", "weird"],
  },
  {
    id: "competitive-grandparent",
    emoji: "🧶",
    name: "The Overly Competitive Grandparent",
    description:
      "You love them enormously and you will still beat them at everything.",
    energy: ["Sweet", "Ruthless", "Nostalgic"],
    act: [
      "Turn anything into a contest.",
      "Offer snacks aggressively.",
      "Recall a victory from 1974.",
    ],
    dress: "Cardigan, comfortable shoes, one championship-level accessory.",
    voice: "Warm, then suddenly steely.",
    rule: "Keep score of something invisible all night.",
    starter: "Sit down, sweetheart. Eat something. Then I'll destroy you.",
    tags: ["funny", "wholesome"],
  },
  {
    id: "new-to-internet",
    emoji: "💾",
    name: "The Person Who Just Discovered The Internet",
    description:
      "You went online yesterday and it has been a lot.",
    energy: ["Overwhelmed", "Excited", "Innocent"],
    act: [
      "Report things you “read online.”",
      "Say website names in full, formally.",
      "Ask if things can be downloaded.",
    ],
    dress: "Very normal. Suspiciously normal.",
    voice: "Wide-eyed, enthusiastic.",
    rule: "Ask at least once if this is happening in real time.",
    starter: "So I've been on the World Wide Web. We should talk.",
    tags: ["funny", "weird"],
  },
  {
    id: "everyone-is-a-spy",
    emoji: "🕶️",
    name: "The Person Who Thinks Everyone Is A Spy",
    description:
      "Everyone in this room is on assignment. Except possibly you.",
    energy: ["Paranoid", "Whispering", "Charming"],
    act: [
      "Assign a codename to each nearby stranger.",
      "Shield your mouth when speaking.",
      "Change seats “for safety.”",
    ],
    dress: "Nondescript. Deliberately forgettable. Sunglasses anyway.",
    voice: "Quiet, quick, urgent.",
    rule: "Never say anything important at full volume.",
    starter: "Act normal. Two of them followed us in.",
    tags: ["funny", "mysterious", "weird"],
  },
  {
    id: "alien-anthropologist",
    emoji: "🛸",
    name: "The Alien Trying To Understand Human Behaviour",
    description:
      "You are gathering data on romance and your notes are going badly.",
    energy: ["Analytical", "Sincere", "Odd"],
    act: [
      "Ask why humans do ordinary things.",
      "Record findings out loud.",
      "Imitate emotions half a beat late.",
    ],
    dress: "Immaculate, slightly off. Something buttoned wrong on purpose.",
    voice: "Flat, curious, precise.",
    rule: "End sentences with “Fascinating.” now and then.",
    starter: "Explain this to me: why do humans share food they enjoy?",
    tags: ["weird", "funny"],
  },
  {
    id: "traveler-1842",
    emoji: "🕰️",
    name: "The Time Traveller Who Thinks It's 1842",
    description:
      "You are certain of the year and everything around you is deeply upsetting.",
    energy: ["Formal", "Alarmed", "Gallant"],
    act: [
      "Be scandalised by clothing and lighting.",
      "Address them with excessive courtesy.",
      "Refuse to touch modern devices.",
    ],
    dress: "Anything that reads as period: waistcoat, high neckline, boots.",
    voice: "Old-fashioned, formal, breathless.",
    rule: "Refuse to accept that it is not 1842.",
    starter: "Madam, sir — forgive me. Where has the carriage gone?",
    tags: ["funny", "weird", "cinematic"],
  },
  {
    id: "barista",
    emoji: "☕",
    name: "The Exhausted Barista",
    description:
      "You have made 400 drinks today and you are running on fumes and gossip.",
    energy: ["Deadpan", "Funny", "Frayed"],
    act: [
      "Judge everyone's order silently, then aloud.",
      "Explain beans passionately for too long.",
      "Sigh at the sound of a milk steamer.",
    ],
    dress: "Apron energy. Rolled sleeves. Slight coffee stain.",
    voice: "Flat, dry, occasionally unhinged.",
    rule: "Take their order at least once tonight, unprompted.",
    starter: "Name for the order? Actually, don't — I'll spell it wrong anyway.",
    tags: ["funny", "wholesome"],
  },
  {
    id: "lighthouse-keeper",
    emoji: "🌊",
    name: "The Lighthouse Keeper",
    description:
      "You have spent a long time alone with the weather and you notice everything.",
    energy: ["Quiet", "Deep", "Tender"],
    act: [
      "Talk about the sea unprompted.",
      "Notice small things nobody mentions.",
      "Fall into comfortable silence.",
    ],
    dress: "Thick knit, weatherproof coat, salt-and-wind hair.",
    voice: "Slow, low, gentle.",
    rule: "Compare something tonight to a storm you survived.",
    starter: "I don't get many visitors. You'll have to forgive the staring.",
    tags: ["romantic", "wholesome", "mysterious"],
  },
  {
    id: "florist",
    emoji: "🌸",
    name: "The Neighbourhood Florist",
    description:
      "You believe every person has a flower and you've already picked theirs.",
    energy: ["Warm", "Observant", "Romantic"],
    act: [
      "Assign flowers to strangers.",
      "Talk about seasons like people.",
      "Rearrange anything on the table.",
    ],
    dress: "Soft layers, rolled sleeves, something tucked behind your ear.",
    voice: "Gentle, easy, smiling.",
    rule: "Tell them what flower they are — and defend it.",
    starter: "You're a ranunculus. I know. It surprised me too.",
    tags: ["wholesome", "romantic"],
  },
  {
    id: "night-radio-host",
    emoji: "🎙️",
    name: "The Late-Night Radio Host",
    description:
      "It's 2am somewhere and you're taking calls from the heart.",
    energy: ["Smooth", "Intimate", "Nocturnal"],
    act: [
      "Introduce moments like songs.",
      "Speak to an imaginary listener.",
      "Lower your voice to almost nothing.",
    ],
    dress: "Dark, simple, headphones around the neck if you have them.",
    voice: "Velvet. Slow. Very close to the mic.",
    rule: "Dedicate one moment tonight to “everyone still awake.”",
    starter: "You're listening to the quiet hours. Stay with me.",
    tags: ["romantic", "cinematic", "mysterious"],
  },
  {
    id: "heist-driver",
    emoji: "🚗",
    name: "The Getaway Driver",
    description:
      "You're between jobs. Sort of. The engine's still warm.",
    energy: ["Cool", "Twitchy", "Loyal"],
    act: [
      "Time everything.",
      "Plan the exit route out loud.",
      "Refuse to sit with your back to the door.",
    ],
    dress: "Jacket, gloves optional, keys always in hand.",
    voice: "Clipped, calm, low.",
    rule: "Announce how long everything will take, to the second.",
    starter: "We've got ninety minutes. Then I have to be somewhere else.",
    tags: ["cinematic", "mysterious"],
  },
  {
    id: "botanist",
    emoji: "🪴",
    name: "The Devoted Botanist",
    description:
      "You've named your plants and you would like to introduce them.",
    energy: ["Soft", "Nerdy", "Sincere"],
    act: [
      "Check every plant in the venue.",
      "Use latin names casually.",
      "Water something that doesn't need it.",
    ],
    dress: "Earth tones, rolled cuffs, dirt under one fingernail.",
    voice: "Quiet enthusiasm, unstoppable once started.",
    rule: "Introduce one imaginary plant by name.",
    starter: "Before we start — that fern by the door is thriving. I checked.",
    tags: ["wholesome", "weird"],
  },
  {
    id: "opera-singer",
    emoji: "🎼",
    name: "The Retired Opera Singer",
    description:
      "You feel everything at full volume, including menus.",
    energy: ["Grand", "Emotional", "Hilarious"],
    act: [
      "React to news with operatic devastation.",
      "Project across the table.",
      "Sigh in three acts.",
    ],
    dress: "Scarf, dramatic coat, jewellery with a past.",
    voice: "Enormous. Trembling. Beautiful.",
    rule: "Deliver one ordinary sentence as if it's your final aria.",
    starter: "Ah! You came. My heart. My night. My reservation.",
    tags: ["cinematic", "funny", "romantic"],
  },
  {
    id: "mountaineer",
    emoji: "🏔️",
    name: "The Mountaineer",
    description:
      "You came down from altitude for this and the air here feels thick.",
    energy: ["Hardy", "Understated", "Awed"],
    act: [
      "Treat stairs as a summit push.",
      "Check the weather constantly.",
      "Describe views nobody else has seen.",
    ],
    dress: "Technical jacket, boots, sunburnt nose.",
    voice: "Sparse, honest, warm.",
    rule: "Refer to the evening in stages, like a climb.",
    starter: "Base camp. Good. We move for the summit around dessert.",
    tags: ["wholesome", "funny"],
  },
  {
    id: "auctioneer",
    emoji: "🔨",
    name: "The Auctioneer",
    description:
      "Everything has a price and you can find it in under nine seconds.",
    energy: ["Rapid", "Theatrical", "Sharp"],
    act: [
      "Open bidding on ordinary objects.",
      "Speak in bursts of speed.",
      "Slam an imaginary gavel.",
    ],
    dress: "Suit, pocket square, watch you keep checking.",
    voice: "Fast, rhythmic, sudden stops.",
    rule: "Sell one item on the table to an imaginary buyer.",
    starter: "Do I hear ten for the seat beside you? Sold. To me.",
    tags: ["funny", "cinematic"],
  },
  {
    id: "monk",
    emoji: "🕯️",
    name: "The Wandering Monk",
    description:
      "You've walked a long way and you have very little to say and all of it lands.",
    energy: ["Serene", "Present", "Disarming"],
    act: [
      "Answer questions with better questions.",
      "Notice breathing. Yours and theirs.",
      "Be delighted by simple things.",
    ],
    dress: "Simple, loose, undyed. No accessories at all.",
    voice: "Slow, kind, unbothered.",
    rule: "Say nothing at all for one full minute at some point.",
    starter: "I have walked since morning. This chair is a miracle.",
    tags: ["wholesome", "mysterious"],
  },
  {
    id: "gallery-thief",
    emoji: "🖤",
    name: "The Gentleman Thief",
    description:
      "You only steal beautiful things, and you always return the ones with feelings.",
    energy: ["Charming", "Slippery", "Elegant"],
    act: [
      "Compliment security arrangements.",
      "Palm small objects and return them.",
      "Change the subject beautifully.",
    ],
    dress: "Black, tailored, gloves you never explain.",
    voice: "Warm, amused, unhurried.",
    rule: "“Borrow” one small object and confess before the night ends.",
    starter: "Relax. I'm off duty. Mostly.",
    tags: ["romantic", "mysterious", "cinematic"],
  },
];

export const CHARACTERS_BY_ID = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c]),
) as Record<string, Character>;
